### ISSUE TITLE
Scene file 'CharacterSelect.tscn' and 'Title.tscn' appears to be invalid/corrupt.

### ISSUE THREAD

**Issue by RepeatedKibbles** [Techokami/SonicWorldsNext#46]
There is a way to fix this? (Sorry if I sounded weird or mean)

**Comment by DimensionWarped** [comment]
Can you specify which branch and revision you were using?

**Comment by RepeatedKibbles** [comment]
> Can you specify which branch and revision you were using?

I'm using Main Branch meaning Godot 4 update. (Sorry if I sounded weird or mean)

**Comment by Techokami** [comment]
Yeah I can confirm that this is happening. I take blame for this one as I was kind of in a rush last night (because work) so I didn't check things over well enough. We had something similar happen with the test level scene file not too long ago (claims to be corrupt but actually works fine?) and Sharb *thinks* it has to do with the editor configuration? DW, if you're not seeing this error, mind doing a comparison between your local copy of the repo and a fresh download of the repo? Would be nice to nail this down once and for all.

**Comment by Techokami** [comment]
Turns out the problem was due to preloading the Character Select scene in the Title script. Changing it to use "load" instead solves the issue.
