### ISSUE TITLE
About the renderer (Godot 4)

### ISSUE THREAD

**Issue by MetalMaxMX** [Techokami/SonicWorldsNext#48]
Hi! I just cloned your project and I noticed that it was using the Forward+ renderer, which is to say, that is a Vulkan project. Would the Godot 4 port of Sonic Worlds Next also work on the Compatibility renderer (OpenGL) of Godot 4, specially as this gives us a few additional targets (like web for instance) and more? Or does the project uses features that the Forward+ renderer only has? Would like to know. 

Cheers!
MetalMaxMX

**Comment by DimensionWarped** [comment]
The only visual effect I can think of that might be platform specific is character palette cycling for stuff like Super Sonic... and I have no idea if that's actually the case.

**Comment by whitelilydragon** [comment]
I am using Compatibility Mode, to target a broader range of PCs, and the most I have seen disappear are the additive glow effects attached to rings. (Which, depending on the kind of pixel art game you could want to make, wouldn't fit into certain aesthetics anyway.)

Otherwise, Worlds Next Just Works™ with either renderer!

**Comment by DimensionWarped** [comment]
Sounds like everything is square then. We can move this to a discussion if there are things that need to be uncovered rather than confirmed issues.
